version: '3.14'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo